//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStock.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCDbStockEntities : DbContext
    {
        public MVCDbStockEntities()
            : base("name=MVCDbStockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLCATEGORy> TBLCATEGORIES { get; set; }
        public virtual DbSet<TBLCUSTOMER> TBLCUSTOMERS { get; set; }
        public virtual DbSet<TBLPRODUCT> TBLPRODUCTS { get; set; }
        public virtual DbSet<TBLSALE> TBLSALES { get; set; }
    }
}
