//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLCUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCUSTOMER()
        {
            this.TBLSALES = new HashSet<TBLSALE>();
        }
    
        public int CUSTOMERID { get; set; }
        [Required(ErrorMessage ="You can't leave customer first name field empty!")]
        [StringLength(50,ErrorMessage = "You can enter a first name of up to 50 characters.")]
        public string CUSTOMERFIRSTNAME { get; set; }
        [Required(ErrorMessage = "You can't leave customer last name field empty!")]
        [StringLength(50, ErrorMessage = "You can enter a last name of up to 50 characters.")]
        public string CUSTOMERLASTNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSALE> TBLSALES { get; set; }
    }
}
